services:
  vfb-kb:
    scale: 1
  vfb-triplestore:
    scale: 1
  vfb-prod:
    scale: 1
  vfb-kb2kb:
    scale: 1
  vfb-validatekb:
    scale: 1
  vfb-collectdata:
    scale: 1
  vfb-updatetriplestore:
    scale: 1
  vfb-updateprod:
    scale: 1
  vfb-owlery:
    scale: 1
