services:
  vfb-kb:
    image: virtualflybrain/docker-neo4j-knowledgebase:neo2owl
    environment:
      - NEO4J_AUTH=neo4j/neo
      - NEO4J_dbms_read__only=false
      - NEO4J_dbms_memory_heap_maxSize=6G
      - NEO4J_dbms_memory_heap_initial__size=1G 
    ports:
      - 7474:7474
      - 7687:7687
  vfb-triplestore:
    image: yyz1989/rdf4j:latest
    environment:
      - JVM_PARAMS=-Xms1G -Xmx5G
      - RDF4J_DATA=/data 
    ports:
      - 8080:8080
  vfb-prod:
    image: matentzn/vfb-prod:latest
    environment:
      - NEO4J_AUTH=neo4j/neo
      - NEO4J_dbms_read__only=false
      - NEO4J_dbms_memory_heap_maxSize=3G
      - NEO4J_dbms_memory_heap_initial__size=1G 
    ports:
      - 7473:7474
      - 7686:7687
    healthcheck:
      test: [ "CMD", "wget", "-O", "-", "http://vfb-prod:7473" ]
      interval: 18s
      timeout: 12s
      retries: 3
  vfb-kb2kb:
    image: matentzn/vfb-pipeline-kb2kb:latest
    depends_on:
      - vfb-kb
    links:
      - vfb-kb
    environment:
      - KBpassword=neo4j/neo
      - KBserver=http://vfb-kb:7474
  vfb-validatekb:
    image: matentzn/vfb-pipeline-validatekb:latest
    depends_on:
      - vfb-kb
      - vfb-kb2kb
    links:
      - vfb-kb
    environment:
      - KBpassword=neo4j/neo
      - KBserver=http://vfb-kb:7474
  vfb-collectdata:
    image: matentzn/vfb-pipeline-collectdata:latest
    depends_on:
      - vfb-kb
      - vfb-kb2kb
      - vfb-validatekb
    links:
      - vfb-kb
    environment:
      - KBpassword=neo4j/neo
      - KBserver=http://vfb-kb:7474
    volumes:
      - vfb_data:/out
  vfb-updatetriplestore:
    image: matentzn/vfb-pipeline-updatetriplestore:latest
    depends_on:
      - vfb-collectdata
      - vfb-triplestore
    links:
      - vfb-triplestore
    environment:
      - SERVER=http://vfb-triplestore:8080
    volumes:
      - vfb_data:/data
  vfb-updateprod:
    image: matentzn/vfb-pipeline-update-prod:latest
    depends_on:
      - vfb-updatetriplestore
      - vfb-triplestore
      - vfb-prod
    links:
      - vfb-triplestore
    environment:
      - password=neo4j/neo
      - server=http://vfb-prod:7474
      - IMPORT=http://vfb-triplestore:8080/rdf4j-server/repositories/vfb?query=PREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX+owl%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0APREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX+obo%3A+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2F%3E%0ACONSTRUCT+%7B%3Fx+%3Fy+%3Fz%7D%0AWHERE+%7B%0A%09%3Fx+%3Fy+%3Fz+.%0A%7D%0A
  vfb-owlery:
    image: virtualflybrain/owlery-vfb:latest
    depends_on:
      - vfb-updatetriplestore
      - vfb-triplestore
    links:
      - vfb-triplestore
    environment:
      - OWLURL=http://vfb-triplestore:8080/rdf4j-server/repositories/vfb?query=PREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX+owl%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0APREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX+obo%3A+%3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2F%3E%0ACONSTRUCT+%7B%3Fx+%3Fy+%3Fz%7D%0AWHERE+%7B%0A%09%3Fx+%3Fy+%3Fz+.%0A%7D%0A
volumes:
  vfb_data:
